apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deploy-db
  labels:
    app: customer-db
spec:
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: customer-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: dbPass

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: dbName
                  name: map-config

---
apiVersion: v1
kind: Service
metadata:
  name: customer-db-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: customer-db
