apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-ms-deployment
  labels:
    app: customer-ms
spec:
  selector:
    matchLabels:
      app: customer-ms
  template:
    metadata:
      labels:
        app: customer-ms
    spec:
      containers:
        - name: customer-microservice
          image: jpelegrino/customer-ms:1.1
          ports:
            - containerPort: 80
          env:
            - name: CUSTOMER_HOST_K8
              valueFrom:
                configMapKeyRef:
                  name: map-config
                  key: dbHost

            - name: CUSTOMER_DB_K8
              valueFrom:
                configMapKeyRef:
                  name: map-config
                  key: dbName

            - name: CUSTOMER_USER_K8
              valueFrom:
                configMapKeyRef:
                  name: map-config
                  key: dbUser
            - name: CUSTOMER_PASS_K8
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: dbPass

---
apiVersion: v1
kind: Service
metadata:
  name: customer-ms-service
spec:
  selector:
    app: customer-ms
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
