apiVersion: v1
kind: Pod
metadata:
  name: wire-transfer-ms-pod
  labels:
    app: wire-transfer-demo
    name: wire-transfer-ms-pod
spec:
  containers:
    - name: wire-transfer-ms
      image: jpelegrino/wire-transfer-ms:1.1
      ports:
        - containerPort: 80
